security:
    # Encodage des mots de passe
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # Définir le fournisseur de l'utilisateur
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    # Configurer les firewalls pour l'authentification
    firewalls:
        # Permet aux outils de développement de fonctionner
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # Firewall principal
        main:
            # Utilisation de la session Symfony et du provider
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\LoginFormAuthenticator
            # La route de déconnexion
            logout:
                path: app_logout

            # Configurer la "souvenir de moi"
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800  # Durée du cookie de "remember me"
                path: /

    # Définir les accès aux routes selon les rôles
    access_control:
        # Routes accessibles par un admin uniquement
        - { path: ^/admin, roles: ROLE_ADMIN }
        # Routes accessibles par un bibliothécaire uniquement
        - { path: ^/librarian, roles: ROLE_LIBRARIAN }
        # Routes accessibles par un utilisateur uniquement
        - { path: ^/account, roles: ROLE_USER }

    # Optionnel : configuration des règles d'autorisation des utilisateurs
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_LIBRARIAN:   ROLE_USER
